apiVersion: apps/v1
kind: Deployment
metadata:
  name: authms-deployment
  namespace: blog-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: authms-container
          image: medhakommana/auth931:v10
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: authms-secret

